package main

import (
	//"fmt"
	"os"
	"os/signal"
	"runtime"
	"syscall"
	"unsafe"
)

var (
	user32                  = syscall.NewLazyDLL("user32.dll")
	procSetWindowsHookExW   = user32.NewProc("SetWindowsHookExW")
	procUnhookWindowsHookEx = user32.NewProc("UnhookWindowsHookEx")
	procCallNextHookEx      = user32.NewProc("CallNextHookEx")
	procGetMessageW         = user32.NewProc("GetMessageW")
)

const WH_MOUSE_LL = 14

const (

	// Low-level keyboard hook flag
	LLKHF_INJECTED = 0x00000010
	// mouse:
	LLMHF_INJECTED = 0x00000001
)

type POINT struct {
	X, Y int32
}
type MSLLHOOKSTRUCT struct {
	Pt          POINT
	MouseData   uint32
	Flags       uint32
	Time        uint32
	DwExtraInfo uintptr
}

func main() {
	runtime.GOMAXPROCS(2)
	runtime.LockOSThread()

	// EMULATE BACKGROUND NOISE:
	// This forces the Go Runtime to manage multiple goroutines and GC cycles
	go func() {
		for {
			_ = make([]byte, 1024) // Constant tiny allocations to keep GC "warm"
			runtime.Gosched()
		}
	}()

	// 1. Setup the most basic callback possible
	callback := syscall.NewCallback(func(nCode int, wParam, lParam uintptr) uintptr {
		// Just pass it through. No logic, no checks, no nothing.
		//fmt.Printf("works")
		if nCode < 0 {
			ret, _, _ := procCallNextHookEx.Call(0, uintptr(nCode), wParam, lParam)
			return ret
		}
		info := (*MSLLHOOKSTRUCT)(unsafe.Pointer(lParam))
		if info.Flags&LLMHF_INJECTED != 0 {
			// This mouse event was generated by SendInput
			// Do NOT treat it as user input
			ret, _, _ := procCallNextHookEx.Call(0, uintptr(nCode), wParam, lParam)
			return ret
		}

		ret, _, _ := procCallNextHookEx.Call(0, uintptr(nCode), wParam, lParam)
		return ret
	})

	// 2. Install the hook
	hhk, _, _ := procSetWindowsHookExW.Call(WH_MOUSE_LL, callback, 0, 0)
	if hhk == 0 {
		panic("Failed to install hook")
	}

	// 3. Handle Ctrl+C to exit (not strictly needed for the test, but polite)
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		procUnhookWindowsHookEx.Call(hhk)
		os.Exit(0)
	}()

	// 4. The Message Loop (The "Engine" Windows requires for hooks)
	var msg struct {
		hwnd    uintptr
		message uint32
		wParam  uintptr
		lParam  uintptr
		time    uint32
		pt      struct{ x, y int32 }
	}

	for {
		// This blocks until a message arrives
		ret, _, _ := procGetMessageW.Call(uintptr(unsafe.Pointer(&msg)), 0, 0, 0)
		if ret == 0 {
			break
		}
		/*
					Why Hooks don't need Dispatch

			In a normal window setup, you need DispatchMessage to send a message to a WndProc. But Low-Level Hooks (WH_MOUSE_LL) are not
			window messages.

			When you install a Low-Level Hook, the OS injects a requirement into your thread: "Whenever the mouse moves, pause the system
			 and run this specific callback function on this thread."

			The OS's Hook Manager doesn't wait for DispatchMessage. Instead, it intercepts your thread while it is inside the GetMessage
			 (or PeekMessage) call.

			    The flow: GetMessage is called → The OS sees there's a mouse event → The OS executes your mouseProc callback directly
				while the thread is still "inside" the GetMessage syscall → Your callback returns → GetMessage finally returns to your loop with a (potentially unrelated) message.
		*/
	}
}
